#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys

# cat <<!

# Boot took $(uptime | awk '{print $1}') seconds

#         _       _     __ _                  
#   /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
#  /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
# / /\/\ \ | | | | | / /__| | | | | |_| |>  < 
# \/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 

# Welcome to Mini Linux!

# !
echo "Welcome to Mini Linux!"
#exec setsid cttyhack sh
exec /bin/sh
